[package]
name = "cli_todo_list"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
clap = { version = "4.5.8", features = ["derive"] }
thiserror = "1.0.61"
tracing = "0.1"
tracing-subscriber = "0.3"