[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
shared-lib = { path = "../shared-lib" }

tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
mockall = "0.13.0"
async-trait = "0.1.82"
log = "0.4.22"